### ISSUE TITLE
关于“[强制]对于值为true的属性，省去值部分”

### ISSUE THREAD

**Issue by errorrik** [ecomfe/spec#44]
这个貌似会有坑？

**Comment by otakustay** [comment]
有啥坑么，jsx的语法上不写值就是`true`，而不是HTML中的有各种情况

**Comment by errorrik** [comment]
> jsx的语法上不写值就是true
如果是这个逻辑，不是HTML的逻辑就没问题。我只是不确定jsx的逻辑，有具体描述么

**Comment by otakustay** [comment]
Props Default to "True"
If you pass no value for a prop, it defaults to true. These two JSX expressions are equivalent:

<MyTextBox autocomplete />

<MyTextBox autocomplete={true} />
In general, we don't recommend using this because it can be confused with the ES6 object shorthand {foo} which is short for {foo: foo} rather than {foo: true}. This behavior is just there so that it matches the behavior of HTML.
